ChaldeanCatholicPrayerApp/ChaldeanCatholicPrayerApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ChaldeanCatholicPrayerApp/base/urls.py
from django.urls import path
from. import views

urlpatterns = [
    path('login', views.loginPage, name="login"),
    path('logout', views.logoutUser, name="logout"),
    path('register', views.registerPage, name="register"),

    path('', views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('profile/<str:pk>/', views.profilePage, name="user-profile"),

    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-comment/<str:pk>/', views.deleteComment, name="delete-comment"),
    path('update-user/', views.updateUser, name="update-user"),
    path('topics/', views.topicsPage, name="topics"),
    path('activity/', views.activityPage, name="activity"),
]

ChaldeanCatholicPrayerApp/base/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class userProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    userName = models.CharField(max_length=200, null=True)
    biography = models.CharField(max_length=5000, null=True)
    profile_pic = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    EnglishPrayer = models.TextField(null=True, blank=True)
    ChaldeanPrayer = models.TextField(null=True, blank=True)
    commenters = models.ManyToManyField(User, related_name='commenters',blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[:50]

ChaldeanCatholicPrayerApp/base/forms.py
from django.forms import ModelForm
from django import forms
from .models import Room, userProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['commenters']

class CustomUserCreationForm(UserCreationForm):
    name = forms.CharField(max_length=200, required=True, help_text='Fill Name')
    bio = forms.CharField(widget=forms.Textarea, max_length=4000, required=False, help_text='Tell us about yourself')
    profile_pic = forms.ImageField(required=False, help_text='Upload a profile picture')

    class Meta:
        model = User
        fields = ['name','username', 'email', 'bio','profile_pic','password1', 'password2', ]

class CustomUserUpdateForm(forms.ModelForm):
    name = forms.CharField(max_length=200, required=True, help_text='Fill Name')
    bio = forms.CharField(widget=forms.Textarea, max_length=4000, required=False, help_text='Tell us about yourself')
    profile_pic = forms.ImageField(required=False, help_text='Upload a profile picture')

    class Meta:
        model = User
        fields = ['name','username', 'email', 'bio','profile_pic']

ChaldeanCatholicPrayerApp/base/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.db.models import Q, Count
from .models import Room, Topic, Comment, userProfile
from .forms import RoomForm, CustomUserCreationForm, CustomUserUpdateForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm



#rooms = [
#    {'id': 1, 'name': 'Rumsha Prayers'},
#    {'id': 2, 'name': 'Pray the Rosary'},
#    {'id': 3, 'name': 'Mass Liturgy'},
#]

def loginPage(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Invalid Login')

    context = {'page' : page}
    return render(request, 'base/login_register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('home')

def registerPage(request):
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()

            name = form.cleaned_data.get('name')
            bio = form.cleaned_data.get('bio')
            profile_pic = form.cleaned_data.get('profile_pic')
            user_profile = userProfile.objects.create(
                user=user,
                name=name,
                userName=user.username,
                biography=bio,
                profile_pic=profile_pic
            )

            login(request, user)
            return redirect('home')
        else:
            messages.error(request, form.errors)
    return render(request, 'base/login_register.html', {'form':form})

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
        )
    topics = Topic.objects.annotate(num_rooms=Count('room')).order_by('-num_rooms')[:5]

    room_count = rooms.count()
    room_comments = Comment.objects.filter(Q(room__topic__name__icontains=q))

    profile = None
    if request.user.is_authenticated:
        profile = userProfile.objects.get(user=request.user)

    user_profile = None
    if request.user.is_authenticated:
        user_profile = userProfile.objects.get(user=request.user)

    context = {'rooms' : rooms, 'topics' : topics, 'room_count':room_count, 'room_comments':room_comments, 'profile':profile, 'user_profile':user_profile}
    return render(request, 'base/home.html', context)

def room(request, pk):
    room = Room.objects.get(id=pk)
    room_comments = room.comment_set.all().order_by('-created')
    commenters = room.commenters.all()
    other_rooms = Room.objects.exclude(id=pk)[:9]

    if request.method == 'POST':
        comment = Comment.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        return redirect('room', pk=room.id)
    
    user_profile = None
    if request.user.is_authenticated:
        user_profile = userProfile.objects.get(user=request.user)


    context = {'room': room, 'room_comments':room_comments, 'commenters':commenters, 'other_rooms': other_rooms, 'user_profile':user_profile}
    return render(request, 'base/room.html', context)

def createProfile(request, pk):
    user = User.objects.get(id=pk)
    comments = user.comment_set.all()
    topics = Topic.objects.all()
    context = {'user':user, 'comments': comments, 'topics':topics}
    return render(request, 'base/profile.html', context)

@login_required(login_url='login')
def createRoom(request):
    form = RoomForm()
    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
        
    user_profile = None
    if request.user.is_authenticated:
        user_profile = userProfile.objects.get(user=request.user)


    context = {'form': form, 'user_profile':user_profile}
    return render(request, 'base/room_form.html', context)

@login_required(login_url='login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)

    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('home')
        
    user_profile = None
    if request.user.is_authenticated:
        user_profile = userProfile.objects.get(user=request.user)

    context = {'form': form, 'user_profile':user_profile}
    return render(request, 'base/room_form.html', context)

@login_required(login_url='login')
def deleteRoom(request,pk):
    room = Room.objects.get(id=pk)
    if request.method == 'POST':
        room.delete()
        return redirect('home')
    
    user_profile = None
    if request.user.is_authenticated:
        user_profile = userProfile.objects.get(user=request.user)

    context = {'user_profile':user_profile, 'obj':room}

    return render(request, 'base/delete.html', context)

@login_required(login_url='login')
def deleteComment(request,pk):
    comment = Comment.objects.get(id=pk)

    if request.user != comment.user:
        return HttpResponse('You are not able to perform this deletion')

    if request.method == 'POST':
        comment.delete()
        return redirect('home')
    
    user_profile = None
    if request.user.is_authenticated:
        user_profile = userProfile.objects.get(user=request.user)
    
    context = {'user_profile':user_profile,'obj':comment}
    return render(request, 'base/delete.html', context)

@login_required(login_url='login')
def updateUser(request):
    user = request.user
    profile = userProfile.objects.get(user=user)

    madeData = {'bio':profile.biography, 'name':profile.name, 'profilePic': profile.profile_pic}
    form = CustomUserUpdateForm(instance=user, initial = madeData)

    if request.method == 'POST':
        form = CustomUserUpdateForm(request.POST, request.FILES, instance=user)

        if form.is_valid():
            user = form.save(commit = False)
            user.save()

            name = form.cleaned_data.get('name')
            bio = form.cleaned_data.get('bio')
            profile_pic = form.cleaned_data.get('profile_pic')
            profile.name = name
            profile.biography = bio
            
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            return redirect('user-profile', pk=user.id)
        
    user_profile = None
    if request.user.is_authenticated:
        user_profile = userProfile.objects.get(user=request.user)

    context = {'form':form, 'profile':profile, 'user_profile':user_profile}
    return render(request, 'base/update_user.html', context)

def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    topics = Topic.objects.annotate(num_rooms=Count('room')).order_by('-num_rooms')

    user_profile = None
    if request.user.is_authenticated:
        user_profile = userProfile.objects.get(user=request.user)

    context = {'user_profile':user_profile, 'topics':topics}

    return render(request, 'base/topics.html', context)

def activityPage(request):
    
    room_comments = Comment.objects.all()
    user_profile = None
    if request.user.is_authenticated:
        user_profile = userProfile.objects.get(user=request.user)

    context = {'user_profile':user_profile, 'room_comments':room_comments}


    return render(request, 'base/activity.html', context)

def profilePage(request, pk):
    user = User.objects.get(id=pk)
    profile = userProfile.objects.get(user=user)
    comments = Comment.objects.filter(user=user)
    topics = Topic.objects.annotate(num_rooms=Count('room')).order_by('-num_rooms')[:5]

    bio = profile.biography
    min_length = 200

    if (len(bio)) < min_length:
        bio += " &nbsp " * (min_length - len(bio))

    user_profile = None
    if request.user.is_authenticated:
        user_profile = userProfile.objects.get(user=request.user)

    context = {'user':user, 'profile':profile, 'comments':comments, 'topics':topics, 'padded_bio':bio, 'user_profile':user_profile}

    return render(request, 'base/profile.html', context)

ChaldeanCatholicPrayerApp/base/templates/base/activity.html
{% extends "main.html" %}

{% load static %}

{% block content %}
    <main class="layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Recent Activities</h3>
            </div>
          </div>

          <div class="activities-page layout__body">

            {% for comment in room_comments %}
        <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' comment.user.id %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
                {% if comment.user.userprofile and comment.user.userprofile.profile_pic %}
                <img src="{{comment.user.userprofile.profile_pic.url}}"/>
              {% else %}
                <img src="{% static 'images/avatar.svg' %}" />
              {% endif %}
            </div>
            <p>
                {{comment.user.username}}
                <span>{{comment.created|timesince}} ago</span>
            </p>
            </a>
             {% if request.user == comment.user %}
            <div class="roomListRoom__actions">
            <a href="{% url 'delete-comment' comment.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>remove</title>
                <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                ></path>
                </svg>
            </a>
            </div>
            {% endif %}
        </div>
        <div class="activities__boxContent">
            <p>commented on <a href="{% url 'room' comment.room.id %}">{{comment.room}}</a></p>
            <div class="activities__boxRoomContent">
            {{comment}}
            </div>
        </div>
        </div>
        {% endfor %}
          </div>
        </div>
      </div>
    </main>
{% endblock content %}

ChaldeanCatholicPrayerApp/base/templates/base/activity_component.html
{% load static %}
<div class="activities">
        <div class="activities__header">
        <h2>Recent Activities</h2>
        </div>
        {% for comment in room_comments %}
        <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' comment.user.id %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
              {% if comment.user.userprofile and comment.user.userprofile.profile_pic %}
                <img src="{{comment.user.userprofile.profile_pic.url}}"/>
              {% else %}
                <img src="{% static 'images/avatar.svg' %}" />
              {% endif %}
            </div>
            <p>
                @{{comment.user.username}}
                <span>{{comment.created|timesince}} ago</span>
            </p>
            </a>
             {% if request.user == comment.user %}
            <div class="roomListRoom__actions">
            <a href="{% url 'delete-comment' comment.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>remove</title>
                <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                ></path>
                </svg>
            </a>
            </div>
            {% endif %}
        </div>
        <div class="activities__boxContent">
            <p>commented on <a href="{% url 'room' comment.room.id %}">{{comment.room}}</a></p>
            <div class="activities__boxRoomContent">
            {{comment}}
            </div>
        </div>
        </div>
        {% endfor %}
    </div>

ChaldeanCatholicPrayerApp/base/templates/base/comment_feed_component.html
         {% for comment in comments %}
         {% load static %}
        <div class="roomListRoom">
        <div class="roomListRoom__content">
            <a href="{% url 'room'  comment.room.id %}">{{comment.body}}</a>
            <p>
            Comment was made regarding {{comment.room}}
            </p>
        </div>
        <div class="roomListRoom__meta">
            <a href="{% url 'room'  comment.room.id %}" class="roomListRoom__joined">
        <div class="header__logo">
            <img src="{% static 'images/clock.svg' %}" alt="clock icon" />
        </div>

        <style>
            .header__logo{
                display: flex;
                align-items: center;
            }

            .header__logo img{
                height: 25px;
                width: auto;
                object-fit: contain;
                margin-right: 0px;
            }
        </style>
            This comment was made {{comment.created|timesince}} ago
            </a>
        </div>
        </div>
         {% empty %}
        <p>This user has not made any comments yet.</p>
    {% endfor %}

<div>

ChaldeanCatholicPrayerApp/base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{ request.META.HTTP_REFERER }}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" method="POST" action="">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete  "{{obj}}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

ChaldeanCatholicPrayerApp/base/templates/base/home_old.html
{% extends 'main.html' %}

{% block content %}

<h1>Home Templates</h1>

<style>
    .home-container{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>


<div class="home-container">

    <div>
        {% include 'base/topics_component.html' %}
    </div>

    <div>
        <h5>{{room_count}} Prayers Shared!</h5>
        <a href="{% url 'create-room' %}">Create Room</a>
        {% include 'base/feed_component.html' %}


    </div>

    <div>
        {% include 'base/activity_component.html' %}
    </div>

    
</div>

{% endblock content %}

ChaldeanCatholicPrayerApp/base/templates/base/login_register_old.html
{% extends 'main.html' %}

{% block content %}

{% if page == 'login' %}
<div>
    <form method="POST" action="">
        {% csrf_token%}

        <label>Username</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label>Password:</label>
        <input type="password" name="password" placeholder="Enter Password">

        <input type="submit" value="Login">

    </form>

    <p>Have not signed up yet?</p>
    <a href="{% url 'register' %}">Sign Up!</a>
</div>
{% else %}
<div>
    <form method="POST" action="">
        {% csrf_token%}
        {{form.as_p}}
    

        <input type="submit" value="Register">

    </form>
    <p>Already signed up?</p>
    <a href="{% url 'login' %}">Sign In!</a>
</div>

{% endif %}

{% endblock content %}

ChaldeanCatholicPrayerApp/base/templates/base/profile.html
{% extends "main.html" %}
{% load static %}


{% block content %}
  <main class="profile-page layout layout--1">
    <div class="container">
      <!-- Topics Start -->
    <div style="margin-right: 40px; width: 500px" >
        {% include 'base/topics_component.html' %}
    </div>
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
            {% if profile.profile_pic %}
              <img src="{{profile.profile_pic.url}}"/>
            {% else %}
              <img src="{% static 'images/avatar.svg' %}" />
            {% endif %}
            </div>
          </div>
          <div class="profile__info">
            <h3>{{profile.name}}</h3>
            <p>@{{user.username}}</p>
            {% if request.user == user %}
            <a href="{% url 'update-user' %}" class="btn btn--main btn--pill">Edit Profile</a>
            {% endif %}
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>
              {{padded_bio|safe|default:"This user has not added a bio yet."}}
            </p>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Comments made by {{user.username}}</a>
            </h2>
          </div>
        </div>
        {% include 'base/comment_feed_component.html' %}

      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      <!-- Activities End -->
    </div>
  </main>
</body>

{% endblock content %}

ChaldeanCatholicPrayerApp/base/templates/base/profile_old.html
{% extends 'main.html' %}

{% block content %}

<style>
    .profile-container{
        display:grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>

<h1>{{user.username}}</h1>

<div class="profile-container">
    <div>
        {% include 'base/topics_component.html' %}
    </div>

    <div>
        {% include 'base/comment_feed_component.html' %}

    </div>
    

</div>

{% endblock content %}

ChaldeanCatholicPrayerApp/base/templates/base/room_form.html
{% extends "main.html" %}

{% block content %}
  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{% url 'home' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create/Update Section</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="" method="POST">
            {% csrf_token %}

            {% for field in form %}
            <div class="form__group">
              <label for="room_name">{{field.label}}</label>
              {{field}}
              <!-- <input id="room_name" name="room_name" type="text" placeholder="E.g. Mastering Python + Django" /> -->
            </div>
            {% endfor %}

            <!-- <div class="form__group">
              <label for="room_topic">Topic</label>
              <input required type="text" name="topic" id="room_topic" list="topic-list" />
              <datalist id="topic-list">
                <select id="room_topic">
                  <option value="">Select your topic</option>
                  <option value="Python">Python</option>
                  <option value="Django">Django</option>
                </select>
              </datalist>

            </div> -->

            <div class="form__action">
              <a class="btn btn--dark" href="#" onclick="history.back(); return false;">Cancel</a>
              <button class="btn btn--main" type="submit">Create Room</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>

  {% endblock %}

ChaldeanCatholicPrayerApp/base/templates/base/room_form_old.html
{% extends 'main.html' %}

{% block content %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit"/>

    </form>
</div>

{% endblock content %}

ChaldeanCatholicPrayerApp/base/templates/base/room_old.html
{% extends 'main.html' %}

{% block content %}

<style>
    .room-container {
        display: grid;
        grid-template-columns: 3fr 1fr;
    }
</style>

<div class="room-container">

    <div>

        <h1>{{ room.name }}</h1>

        <h1>{{ room.description }}</h1>
        {% if room.EnglishPrayer %}
            <p style="font-size: 0.9em; color:#000000;"><strong> English Prayer: </strong>{{room.EnglishPrayer}}</p>
        {% endif %}

        {% if room.ChaldeanPrayer %}
            <p style="font-size: 0.9em; color:#000000;"><strong> Chaldean Prayer: </strong>{{room.ChaldeanPrayer}}</p>
        {% endif %}


        <div class="comment-wrapper">
            <h3>Comments</h3>
            <hr>

            {% for comment in room_comments %}
                <div>
                    {% if request.user == comment.user %}
                    <a href="{% url 'delete-comment' comment.id %}">Delete</a>
                    {% endif %}
                    <small>
                        @<a href = "{% url 'user-profile' comment.user.id %}">{{comment.user.username}}</a>
                        {{ comment.created|timesince}} ago
                    </small>
                    <p>{{ comment.body }}</p>
                    <hr>
                </div>
            {% endfor %}
        </div>

        {% if request.user.is_authenticated %}
        <div class="comment-form">
            <form method="POST" action="">
                {% csrf_token %}
                <input type="text" name="body" placeholder="Write your comment here...">
                <button type="submit">Post</button>
            </form>
        </div>
        {% endif %}

    </div>

    <div>
        <h3>Other Rooms</h3>
        <hr>
        {% for other_room in other_rooms %}
            <div>
                <a href="{% url 'room' other_room.id %}">{{ other_room.name }}</a>
                <p>{{ other_room.description|truncatewords:10 }}</p>
            </div>
        {% empty %}
            <p>No other rooms available.</p>
        {% endfor %}
    </div>

</div>

{% endblock %}

ChaldeanCatholicPrayerApp/base/templates/base/topics_component.html
    <div class="topics">
        <div class="topics__header">
        <h2>Browse Topics</h2>
        </div>
        <ul class="topics__list">
        <li>
            <a href="{% url 'home' %}" class="active">All <span>{{topics.count}}</span></a>
        </li>
        {% for topic in topics %}
        <li>
            <a href="{% url 'home' %}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.all.count}}</span></a>
        </li>
        {% endfor %}
        </ul>
        <a class="btn btn--link" href="{% url 'topics' %}">
        More
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>chevron-down</title>
            <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
        </svg>
        </a>
    </div>

ChaldeanCatholicPrayerApp/base/templates/base/update_user.html
{% extends 'main.html' %}

{% block content %}

    <main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                      {% for field in form %}
                        <div class="form__group">
                            <label for="profile_pic">{{field.label}}</label>
                            {{field}}
                        </div>
                      {% endfor %}

                        <div class="form__action">
                            <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </main>
{% endblock content %}